apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metric-server-helm.yaml
  - karpenter-helm.yaml
  - argo-workflows-helm.yaml
  - tenant-chart-helm.yaml
  - eks-charts-helm.yaml
  - kubecost-helm.yaml